name: Auto tag
on:
  schedule:             # Group PRs in the same tag
    - cron:  '30 5,17 * * 1,2'  # Try some times to allow deps to propagate.
  workflow_dispatch:    # Manual in case needed
jobs:
  dependabot-auto-tag:
    uses: jesusfcro/release-action/.github/workflows/release-workflow.yaml@master
    with:
      author: Jesus Carpintero
