name: Auto tag
on:
  schedule:             # Group PRs in the same tag
    - cron:  '30 5,17 * * 1,2'  # Try some times to allow deps to propagate.
  workflow_dispatch:    # Manual in case needed
jobs:
  dependabot-auto-tag:
    # Validate that workflow_dispatch was on the default_branch.
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-22.04
    permissions:
      contents: write   # Needed to elevate secret.GITHUB_TOKEN permissions.
    steps:
    - uses: jesusfcro/release-action@master
